name: "Release npm Node Project"
description: "Release an npm Node project using semantic-release"
branding:
  icon: upload-cloud
  color: red

inputs:
  node-version:
    description: "Node version"
    required: false
    default: "lts/*"
  npm-token:
    description: "NPM token"
    required: true
  github-token:
    description: "GitHub token"
    required: false
    default: ${{ github.token }}

outputs:
  released:
    description: New version released
    value: ${{ steps.semantic-release.outputs.new_release_published }}
  version:
    description: Version
    value: ${{ steps.semantic-release.outputs.new_release_version }}
  major:
    description: Major version
    value: ${{ steps.semantic-release.outputs.new_release_major_version }}
  minor:
    description: Minor version
    value: ${{ steps.semantic-release.outputs.new_release_minor_version }}
  patch:
    description: Patch version
    value: ${{ steps.semantic-release.outputs.new_release_patch_version }}
  channel:
    description: Release channel
    value: ${{ steps.semantic-release.outputs.new_release_channel }}
  release-notes:
    description: Release notes
    value: ${{ steps.semantic-release.outputs.new_release_notes }}

runs:
  using: "composite"
  steps:
    - name: Get semantic-release version
      shell: sh
      id: semantic-release-version
      run: "echo version=$(npm view @cihelper/semanticrelease-preset-npm dependencies.semantic-release) >> $GITHUB_OUTPUT"
    - name: Run semantic-release
      id: semantic-release
      uses: cycjimmy/semantic-release-action@v3
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
      with:
        semantic_version: ${{ steps.semantic-release-version.outputs.version }}
        extra_plugins: "@cihelper/semanticrelease-preset-npm@1"
        extends: "@cihelper/semanticrelease-preset-npm"
