name: "Release npm Node Project"
description: "Release an npm Node project using semantic-release"
branding:
  icon: upload-cloud
  color: red

inputs:
  node-version:
    description: "Node version"
    required: false
  npm-token:
    description: "NPM token"
    required: false
  github-token:
    description: "GitHub token"
    required: false
    default: ${{ github.token }}
  npm-install:
    description: "Install dependencies from package-lock.json"
    required: false

outputs:
  released:
    description: Whether a new release was published. The return value is in the form of a string. ("true" or "false")
    value: ${{ steps.semantic-release.outputs.new_release_published }}
  version:
    description: Version of the new release. (e.g. "1.3.0")
    value: ${{ steps.semantic-release.outputs.new_release_version }}
  major:
    description: Major version of the new release. (e.g. "1")
    value: ${{ steps.semantic-release.outputs.new_release_major_version }}
  minor:
    description: Minor version of the new release. (e.g. "3")
    value: ${{ steps.semantic-release.outputs.new_release_minor_version }}
  patch:
    description: Patch version of the new release. (e.g. "0")
    value: ${{ steps.semantic-release.outputs.new_release_patch_version }}
  channel:
    description: The distribution channel on which the last release was initially made available (undefined for the default distribution channel).
    value: ${{ steps.semantic-release.outputs.new_release_channel }}
  release-notes:
    description: The release notes for the new release.
    value: ${{ steps.semantic-release.outputs.new_release_notes }}
  git-head:
    description: The sha of the last commit being part of the new release
    value: ${{ steps.semantic-release.outputs.new_release_git_head }}
  git-tag:
    description: The Git tag associated with the new release.
    value: ${{ steps.semantic-release.outputs.new_release_git_tag }}
  prev-version:
    description: Version of the previous release, if there was one. (e.g. "1.2.0")
    value: ${{ steps.semantic-release.outputs.last_release_version }}
  prev-git-head:
    description: The sha of the last commit being part of the last release, if there was one.
    value: ${{ steps.semantic-release.outputs.last_release_git_head }}
  prev-git-tag:
    description: The Git tag associated with the last release, if there was one.
    value: ${{ steps.semantic-release.outputs.last_release_git_tag }}

runs:
  using: "composite"
  steps:
    - name: Setup Node
      if: ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: "${{ inputs.node-version }}"
    - name: Install npm dependencies
      if: ${{ inputs.npm-install }}
      run: npm ci
      shell: sh
    - name: Get semantic-release version
      shell: sh
      id: semantic-release-version
      run: "echo version=$(npm view @cihelper/semanticrelease-preset-npm dependencies.semantic-release) >> $GITHUB_OUTPUT"
    - name: Run semantic-release
      id: semantic-release
      uses: cycjimmy/semantic-release-action@v4
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
        NPM_PREPARE_SCRIPT: ${{ inputs.npm-prepare-script }}
        NPM_INSTALL: ${{ inputs.npm-install }}
      with:
        semantic_version: ${{ steps.semantic-release-version.outputs.version }}
        extra_plugins: "@cihelper/semanticrelease-preset-npm@1"
        extends: "@cihelper/semanticrelease-preset-npm"
